### ISSUE TITLE
Grouping Umbrella Apps

### ISSUE THREAD

**Issue by hpopp** [russmatney/ex_dash#1]
Love the package. Is there a way to combine all of the apps in an umbrella project into a single docset?

**Comment by russmatney** [comment]
@hpopp Likely, but not yet tested/supported! It looks like [ex_doc supports doing so for umbrella apps](https://github.com/elixir-lang/ex_doc/blob/master/lib/mix/tasks/docs.ex#L104), so it shouldn't be too much work from there.

Would you say that's the preferred way for this to work on umbrella apps? I'll probably make it the default in those cases.

**Comment by hpopp** [comment]
Grouping is the default for `mix docs` when run from the umbrella's directory. I can't speak for everyone but that's generally the behavior I'd expect.

**Comment by russmatney** [comment]
@hpopp I have this working on the master branch, but found a few quirks that I'll need to fix before releasing a new version (threading a name option and handling the umbrella app 'version'). If you're looking for something right away, feel free to use it, otherwise I hope to have a release in the next couple days.

**Comment by hpopp** [comment]
No worries, I'm in no rush. Thanks for tackling this so quickly!

**Comment by russmatney** [comment]
Version 0.1.2 groups umbrella apps by default! You probably want to specify a name, and can do that via the CLI: `mix docs.dash --name MyDocSet`. Let me know if anything differs from the usual docs provided from Hex!
